{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-nplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nplyr/nplyr_{{ version }}.tar.gz
  sha256: 749b352af8fa1d6b812b39c854794c4fdc455daf706e8ab12703bab6fe32555a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-purrr
    - r-rlang
    - r-tidyr
  run:
    - r-base
    - r-assertthat
    - r-dplyr
    - r-purrr
    - r-rlang
    - r-tidyr

test:
  commands:
    - $R -e "library('nplyr')"           # [not win]
    - "\"%R%\" -e \"library('nplyr')\""  # [win]

about:
  home: https://github.com/markjrieke/nplyr, https://markjrieke.github.io/nplyr/
  license: MIT
  summary: "Provides functions for manipulating nested data frames in a list-column using 'dplyr' <https://dplyr.tidyverse.org/> syntax. Rather than unnesting, then manipulating a data frame, 'nplyr' allows users to manipulate each nested data frame directly. 'nplyr' is a wrapper for 'dplyr' functions that provide tools
    for common data manipulation steps: filtering rows, selecting columns, summarising grouped data, among others."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
